# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Step 2 - GitHub Action if statement (true)
      run: |
        python3 weibo.py
    - name: Upload to this repo
      run: |
        if [[ -n $(git diff --stat)  ]]
        then
            git config --global user.name "haoge101" # 改成Github账号用户名
            git config --global user.email "haoge101@163.com" # 改成GitHub账号的邮箱
            git add .
            git commit -m "upload"
            git push -u origin main && echo "Git Pushed Origin" # runner改成存放图片的分支    
        else
            echo "nothing to update." 
        fi
